### ISSUE TITLE
Can't connect to websocket -> wrong host

### ISSUE THREAD

**Issue by Sharknoon** [Longor1996/orlytalk#1]
Hi Lars,

first, this is a great App 👍 

Although I have a problem. I have deployed this App on my server [orlytalk.sharknoon.de](https://orlytalk.sharknoon.de) and can't log in because the connection with the websocket fails.

I am on Port 443 (HTTPS) and because this is the default port, `location.port` returns "" (empty String).

And here is the problem, in your `index.ts` you are checking if the Port is `6991`, but in this case it isnt:
https://github.com/Longor1996/orlytalk/blob/c4f7109f220a3221becd5e1840221cfcc5017d24/orly-server/src/www/ts/index.ts#L61

I suggest changing this line to
```ts
 const HOST = location.host + ":" + location.port;
```
or some other mecanics to avoid the localhost host to be selected for standard HTTP and HTTPS ports.

Thanks in advance

Your fan

Josua frank

**Comment by Sharknoon** [comment]
Here are some additional informations:

![image](https://user-images.githubusercontent.com/16149608/94423331-c3f93000-0188-11eb-8eff-f2972072c598.png)

**Comment by Longor1996** [comment]
Sorry about that, should've used the URI-scheme instead!

Fixed in commit e91c1001999bd549c23a8698734aa7dbea22af31
