### ISSUE TITLE
Create Folder and Database File if it doesnt exist already

### ISSUE THREAD

**Issue by Sharknoon** [Longor1996/orlytalk#4]
### Problem:
When specifying an environment variable like `./data/sqlite.db` a folder named `data` needs to be created.

The problem is, that docker volume mounts can only mount directories, not individual files. Therefore a custom directory would be needed.

While you could use a directory from the underlying linux distribution, this would introduce new dependencies to the os.

This is the current implementation:

https://github.com/Longor1996/orlytalk/blob/f4ce721b30a01c500ce258247996610b6dbde191/orly-server/src/main.rs#L31-L39

I would suggest creating all parent directories of the sqlite.db file is they doesnt already exist.

### Another Problem with this solution

when specifying an absolute path like `/etc/orlytalk/sqlite.db` this path gets appended to the working directory. If the path starts at root, the exapth path should be used.

**Comment by Longor1996** [comment]
Solved with commit b228dfa284d9d3d22eb657feab6fdf6d267350c7
